version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/automated-actions/ECS_TASK_PATCHING_AUTOMATION"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/high-availability-endpoint/python"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/high-availability-endpoint/java"
    schedule:
      interval: "weekly"
